# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1anYMPz3wwsFGkGoOQ8ycFcATNyBrgPX_

Import data set
"""

import pandas as pd
df_sales= pd.read_csv("/content/zepto_sales.csv")
df_sales

df_products = pd.read_csv("/content/zepto_products (1).csv")
df_products

"""information of sales"""

df_sales.info()

df_sales.describe()

df_sales.shape

df_sales.head()

df_sales.tail()

"""Information of Products"""

df_products.describe()

df_products.info()

df_products.shape

df_products.head()

df_products.tail()

"""DATA CLEANING"""

df_products.isnull().sum()

df_sales.isnull().sum()

df_sales.dropna(subset=["city","delivery_status"],inplace=True)
print(df_sales[["city","delivery_status"]].isnull().sum())

mean_delivery_time = df_sales["delivery_time_mins"].mean()
df_sales["delivery_time_mins"].fillna(mean_delivery_time,inplace=True)
print(df_sales["delivery_time_mins"].isnull().sum())

df_sales.duplicated().sum()

df_sales.drop_duplicates(inplace=True)

df_sales.shape[0]

df_sales.duplicated().sum()

df_sales["order_date"]= pd.to_datetime(df_sales["order_date"])

"""Data Analysis - Aggregations and Grouping"""

min_amount= df_sales["total_amount"].min()
max_amount= df_sales["total_amount"].max()
average_amount= df_sales["total_amount"].mean()
print(f"\nmin total amount: {min_amount: .2f}")
print(f"\nmax total amont: {max_amount: .2f}")
print(f"\naverage total amont: {average_amount: .2f}")

top_products=df_sales.groupby("product_id")["total_amount"].sum().nlargest(5)
print(top_products)

"""merge"""

top_product_details= top_products.reset_index().merge(df_products,on="product_id")
print(top_product_details[["product_name","category","total_amount"]])

sales_by_city= df_sales.groupby("city")["total_amount"].sum().sort_values(ascending=False)
sales_by_city

average_delivery_time_by_city= df_sales.groupby("city")["delivery_time_mins"].mean().sort_values()
average_delivery_time_by_city

"""sales trend"""

df_sales["month"]=df_sales["order_date"].dt.to_period("M")
monthly_sales=df_sales.groupby("month").total_amount.sum()
monthly_sales

"""sales by product category"""

sales_by_category= df_sales.merge(df_products, on="product_id")
sales_by_category= sales_by_category.groupby("category")["total_amount"].sum().sort_values(ascending=False)
sales_by_category

"""DATA VISUALIZATION USING MATPLOTLIB"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

"""PLOT 1 : TOP 5 PRODUCT BY SALES AMOUNT"""

plt.figure(figsize=(12,7))
sns.barplot(x="product_name",y="total_amount", data=top_product_details,palette="viridis")
plt.title("Top 5 Products by Total Sales Amount")
plt.xlabel("Product Name")
plt.ylabel("Total Sales Amount")
plt.xticks(rotation=45 , ha="right")
plt.tight_layout()
plt.show()

"""Plot 2 :  Total Sales By City"""

plt.figure(figsize=(12,7))
sns.barplot(x=sales_by_city.index,y=sales_by_city.values,palette="magma")
plt.title("Total Sales By City")
plt.xlabel("city")
plt.ylabel("Total Sales Amount")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

"""Plot 3 : Monthly Sales Trend"""

plt.figure(figsize=(12,7))
monthly_sales.plot(kind="line", marker="o", color="#3498DB")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales Amount")
plt.grid=True
plt.tight_layout()
plt.show()

"""Plot 4 : Sales By Product Category"""

plt.figure(figsize=(10,10))
plt.pie(sales_by_category, labels=sales_by_category.index,autopct="%1.1f%%", startangle=140, colors=sns.color_palette("pastel"))
plt.title("Total Sales By Product Category")
plt.axis("equal")
plt.tight_layout()
plt.show()

"""Plot 5 : Distribution Of Delivery Times"""

plt.figure(figsize=(10,6))
sns.histplot(df_sales["delivery_time_mins"],bins=20, kde=True, color="red")
plt.title="Distribution Of delivery times"
plt.xlabel("Delivery Time (minutes)")
plt.ylabel("frequency")
plt.tight_layout()
plt.show()